#!/usr/bin/env python3
"""Validate research consistency + generated GameKnowledge."""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from quest_audit_lib import (  # noqa: E402
    MAIN_ROUTE,
    ROOT,
    SKIP,
    classify_all,
    coverage,
    load_quests,
)
from quest_route_validator import validate as validate_route  # noqa: E402

from build_game_data import RUNTIME_OVERRIDES, apply_overrides  # noqa: E402

# Physical islands + research grouping keys (not world islands 4+).
ISLANDS = {
    "Anchor Town",
    "Clown Town",
    "Maple Village",
    "Skill Mastery",
    "Tutorial",
    "Fighting Style",
    "Crew",
    "",
}
VERIFIED = {"STATIC_VERIFIED", "IMPLEMENTED", "RUNTIME_VERIFIED"}


def fail(code: str, msg: str, errors: list) -> None:
    errors.append(f"{code}: {msg}")


def main() -> int:
    quests = load_quests()
    rows = classify_all(quests)
    apply_overrides(rows)
    names = {q["name"] for q in quests}
    npcs = json.loads((ROOT / "research" / "npcs.json").read_text(encoding="utf-8"))
    errors: list[str] = []
    errors.extend(validate_route(rows, quests))

    by_quest = defaultdict(list)
    for r in rows:
        by_quest[r["quest"]].append(r)

    for q in quests:
        qn = q["name"]
        island = q.get("island") or ""
        if island not in ISLANDS and qn not in SKIP:
            fail("UNKNOWN_ISLAND", f"{qn} island={island!r}", errors)
        for p in q.get("prerequisites") or []:
            if p not in names and p not in SKIP:
                fail("UNRESOLVED_DEPENDENCY", f"{qn} prereq {p}", errors)
        accept = (q.get("accept") or {}).get("npc")
        if accept and accept not in npcs and qn not in SKIP:
            print(f"WARN UNKNOWN_NPC {qn} accept={accept}")
        if q.get("type") == "Repeatable" and qn not in SKIP:
            automatic = q.get("automatic") is True
            npc = accept or q.get("unlock_contact")
            if not automatic and not npc:
                print(f"WARN REPEATABLE_NO_START {qn}")

    for r in rows:
        if r["quest"] not in MAIN_ROUTE:
            continue
        verified = r["status"] in VERIFIED or r.get("confidence") == "STATIC_VERIFIED"
        if verified and (not r.get("handler") or r["handler"] == "UNKNOWN"):
            fail("STATIC_NO_PLAN", f"{r['quest']} {r['objective']} {r['target']}", errors)
        if verified and not r.get("validation"):
            fail("MISSING_VALIDATION", f"{r['quest']} stage {r['stage']}", errors)

    gen = ROOT / "Game" / "GeneratedData.lua"
    if not gen.is_file():
        fail("MISSING_GENERATED", "Game/GeneratedData.lua missing — run tools/build_game_data.py", errors)
    else:
        src = gen.read_text(encoding="utf-8")
        if "GENERATED by tools/build_game_data.py" not in src:
            fail("GENERATED_STALE", "GeneratedData missing compiler banner", errors)
        if "M.Quests" not in src or "M.Stages" not in src:
            fail("GENERATED_STALE", "GeneratedData missing Quests/Stages", errors)

    cov = coverage(rows)
    print(f"quests: {cov['quests']}")
    print(f"stages: {cov['all']['stages']}")
    print(f"implemented: {cov['all']['implemented']}")
    print(f"runtime_required: {cov['all']['runtime_required']}")
    print(f"unresolved: {cov['all']['unresolved']}")
    print(f"main_route implemented: {cov['main_route']['implemented']}/{cov['main_route']['stages']}")
    if errors:
        print("FAIL")
        for e in errors:
            print(e)
        return 1
    print("PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
