#!/usr/bin/env python3
"""Gate: generated root kaitun.lua is a true single-file production chunk."""

from __future__ import annotations

import json
import re
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_single import collect_source_paths, source_hash  # noqa: E402


def fail(msg: str) -> None:
    print(f"[verify_single] FAIL: {msg}")
    raise SystemExit(1)


CALL_HTTP = re.compile(r"(?<![\w.])game:HttpGet\s*\(")
CALL_LOADSTRING = re.compile(r"(?<![\w.])loadstring\s*\(")
PROJECT_REQUIRE = re.compile(
    r"""require\s*\(\s*["'](?:Core|Game|Systems|Progression|src)[/\\.]"""
)
PROJECT_PATH = re.compile(
    r"""["'](?:Core|Game|Systems|Progression)/[A-Za-z0-9_./-]+\.lua["']"""
)


def count_table_keys(src: str, marker: str) -> int:
    idx = src.find(marker)
    if idx < 0:
        return 0
    body = src[idx + len(marker) :]
    nxt = re.search(r"\n\tM\.[A-Za-z]+ = \{", body)
    chunk = body[: nxt.start()] if nxt else body
    quoted = len(re.findall(r'\n\t\t\["(?:[^"\\]|\\.)+"\]\s*=', chunk))
    ident = len(re.findall(r"\n\t\t[A-Za-z_][A-Za-z0-9_]*\s*=\s*\{", chunk))
    return quoted + ident


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    path = root / "kaitun.lua"
    if not path.is_file():
        fail("missing kaitun.lua")
    src = path.read_text(encoding="utf-8")
    version = (root / "VERSION").read_text(encoding="utf-8").strip()
    manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))

    if not src.startswith("--==================================================\n-- GRAND BLUE KAITUN"):
        fail("kaitun.lua is not the generated single-file header")
    if "GENERATED by tools/build_single.py" not in src[:800]:
        fail("kaitun.lua missing generator banner")
    if f'local VERSION = "{version}"' not in src:
        fail("VERSION not embedded")
    if "local BUILD =" not in src:
        fail("BUILD not embedded")
    if "function LoadModule" in src or "local function LoadModule" in src:
        fail("LoadModule still present")
    if "GB_USE_BUNDLE" in src:
        fail("GB_USE_BUNDLE still present")
    if "GB_BASE_URL" in src:
        fail("GB_BASE_URL still present")
    if "return function(meta)" in src:
        fail("old bundle wrapper still present")
    if '["Config.lua"] = [[' in src or "local files = {" in src:
        fail("module-string table still present")
    if "Loaded " in src and "modules" in src:
        fail("module-load boot log still present")

    if CALL_HTTP.search(src):
        fail("live game:HttpGet call in production file")
    # loadstring may appear only inside the teleport requeue string
    for m in CALL_LOADSTRING.finditer(src):
        window = src[max(0, m.start() - 80) : m.start() + 80]
        if "queue_on_teleport" not in src[max(0, m.start() - 400) : m.start() + 200] and "queueSameFile" not in src[max(0, m.start() - 400) : m.start() + 80]:
            fail(f"loadstring outside teleport requeue: {window!r}")

    if PROJECT_REQUIRE.search(src):
        fail("project-owned require() still present")
    if PROJECT_PATH.search(src):
        fail("project module path string still present")

    for marker in (
        "function startSessionLog",
        "queue_on_teleport",
        "function GB.Stop",
        "function GB.Destroy",
        "function GB.SelfCheck",
        "[Kaitun] GrandBlueKaitun v",
        "[Kaitun] Ready in",
        "SourceHttpAfterBoot=0",
        "function M.destroyHit",
        "function M.request",
        "farmSession",
        "GBKaitun/logs/latest.txt",
    ):
        if marker not in src:
            fail(f"missing runtime marker: {marker}")

    hashed = collect_source_paths(root, manifest)
    digest = source_hash(hashed)
    embedded = re.search(r"-- SOURCE_HASH: ([0-9a-f]{16})", src)
    if not embedded:
        fail("SOURCE_HASH missing")
    if embedded.group(1) != digest:
        fail(f"kaitun.lua stale SOURCE_HASH file={embedded.group(1)} expected={digest}")
    build = manifest.get("build") or {}
    if str(build.get("source_hash", "")) != digest:
        fail("manifest.build.source_hash stale")

    quests = count_table_keys(src, "\tM.Quests = {")
    npcs = count_table_keys(src, "\tM.NPCs = {")
    items = count_table_keys(src, "\tM.Items = {")
    skills = count_table_keys(src, "\tM.Skills = {")
    tutorials = count_table_keys(src, "\tM.Tutorials = {")
    if quests < 140:
        fail(f"embedded quests too few: {quests}")
    if npcs < 80:
        fail(f"embedded NPCs too few: {npcs}")
    if items < 80:
        fail(f"embedded items too few: {items}")

    http_count = len(re.findall(r"HttpGet", src))
    loadstring_count = len(re.findall(r"loadstring", src))
    require_count = src.count("require(")
    project_require = len(PROJECT_REQUIRE.findall(src))

    print("[verify_single] OK")
    print(f"[verify_single] version={version}")
    print(f"[verify_single] lines={src.count(chr(10)) + 1}")
    print(f"[verify_single] bytes={len(src.encode('utf-8'))}")
    print(f"[verify_single] source_hash={digest}")
    print(
        f"[verify_single] HttpGet_token={http_count} loadstring_token={loadstring_count} "
        f"require={require_count} project_require={project_require}"
    )
    print(f"[verify_single] quests={quests} npcs={npcs} items={items} skills={skills} tutorials={tutorials}")


if __name__ == "__main__":
    try:
        main()
    except json.JSONDecodeError as exc:
        fail(f"manifest decode: {exc}")
